# Generated by Django 5.2 on 2025-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_token',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
